### ISSUE TITLE
Load local model in Windows

### ISSUE THREAD

**Issue by SlavaDobr** [yhwang/node-red-contrib-tf-model#12]
Hello!

I succeeded in uploading the local model to Linux, but it turned out that the server I needed uses Windows.
Tell me please:
How to load local model in windows?
I tried to specify the absolute path, but this does not work, tried to specify as in Linux:
file://....
Tried through an environment variable
but it doesn’t work either.

Thanks in advance!
With respect!

**Comment by yhwang** [comment]
good to know that you were trying this on Windows. I just verified that in Windows, the returned value of `URL.pathname` would be something like `/c:/Users/yhwang/model.json`. Using such value won't work. One quick workaround is to specify the model path like this would work: `file:///Users/yhwang/model.json` if your model is under `C:`
definitely, need properly handling in windows platform

**Comment by yhwang** [comment]
I fixed the issue of using local file model path in windows. Now you should use local path like this on Windows:
`file:///c:/Users/yhwang/model.json`

**note:** the workaround I mentioned earlier doesn't work now.

**Comment by SlavaDobr** [comment]
It works!
Thank you very much for supporting your node and for such quick answers!
