### ISSUE TITLE
Problem installing node-red-contrib-tf-model

### ISSUE THREAD

**Issue by keekeen** [yhwang/node-red-contrib-tf-model#16]
Hi @yhwang,

Firstly, thank you for sharing this node.

I am having some issue getting the node running on Node-RED and would like to check with you if I have done anything wrong for my setup. I have attached some photos for your reference and the following are done under Docker on Windows.

![Screenshot 2020-12-10 144459](https://user-images.githubusercontent.com/24519970/101748248-472eee80-3b07-11eb-8338-abb1d87550c0.png)
On the above picture, I have run the following commands under the node red data directory:
1. npm install @tensorflow/tfjs-node
2. npm install node-red-contrib-tf-model
However, the return message suggested me to installed version 1.4.0 for @tensorflow/tfjs-node

![Screenshot 2020-12-10 160909](https://user-images.githubusercontent.com/24519970/101748725-e0f69b80-3b07-11eb-951e-49c2c9583fe0.png)
In the above pircture, I have installed version 1.4.0 first before executing "npm install node-red-contrib-tf-model" and got no errors.

![Screenshot 2020-12-10 143712](https://user-images.githubusercontent.com/24519970/101748890-0f747680-3b08-11eb-9aad-7a8378efc4b1.png)
However, it still shows that tf-model node is not available in node-red.

Apologies if I am missing anything here. I would be happy to share any more info that you need.

Thank you very much for your time!!

**Comment by yhwang** [comment]
can you try this inside your docker? 

```
git clone https://github.com/yhwang/node-red-contrib-tf-model.git
cp -r node-red-contrib-tf-model/examples/object-detection .
cd object-detection
```
And follow the instruction here to finish the whole setup: https://github.com/yhwang/node-red-contrib-tf-model/tree/master/examples/object-detection

It that example, it runs node-red from there and everything is inside that directory. It uses https instead of http. If you want to turn https off, you just need to comment out those lines in `settings.js` and restart the Node-RED:
```
    https: {
        key: fs.readFileSync('privatekey.pem'),
        cert: fs.readFileSync('certificate.pem')
    },

    // The following property can be used to cause insecure HTTP connections to
    // be redirected to HTTPS.
    requireHttps: true,
```

**Comment by keekeen** [comment]
Hi @yhwang,

Thank you very much. I am able to get it running within Docker container now.

Cheers
