### ISSUE TITLE
Unable to install 'node-red-contrib-tf-model' on Node-RED

### ISSUE THREAD

**Issue by devittok** [yhwang/node-red-contrib-tf-model#17]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: Windows 10 Home x64
- Node version: 14.15.1
- NPM version: 6.14.9

I followed the tutorials below for the installation of the tensorflow model:

- https://flows.nodered.org/node/node-red-contrib-tf-model
- https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md

1. I first installed the '@tensorflow/tfjs-node' inside Node-RED directly by running the following code
_C:\Users\username.node-red\node_modules> **npm install @tensorflow/tfjs-node@1.4.0**_

2. Ran npm install under C:\Users\username.node-red\node_modules@tensorflow\tfjs-node:
_C:\Users\username.node-red\node_modules@tensorflow\tfjs-node> **npm install**_

3. Finally ran npm install node-red-contrib-tf-model on the same directory:
_C:\Users\username.node-red\node_modules@tensorflow\tfjs-node> **npm install node-red-contrib-tf-model**_

Error that occured:

**npm WARN node-red-contrib-tf-model@0.1.11 requires a peer of @tensorflow/tfjs-node@^1.4.0 but none is installed. You must install peer dependencies yourself. npm WARN @tensorflow/tfjs-node@1.4.0 No license field.**

I have installed the correct tfjs-node version, and so why does this error occur?

Edit: Tried installing the module straight from Node-RED itself and got the following

**_ERROR:The specified module could not be found._**
**_C:\Users\username\.node-red\node_modules\@tensorflow\tfjs-node\lib\napi-v6\tfjs_binding.node_**

When I checked the above directory it turns out that I do have the 'tfjs_binding.node'.

What am I doing wrong here? Can someone please help me out.

**Comment by yhwang** [comment]
@devittok sorry for the late response. did you solve the issue? (I hope so)
