### ISSUE TITLE
Unable to install node-red-contrib-tf-model in Node-RED

### ISSUE THREAD

**Issue by devittok** [yhwang/node-red-contrib-tf-model#18]
Hi @yhwang 

Firstly, thank you for your time for looking into this issue.

I am having difficulties installing the 'node-red-contrib-tf-model' module in Node-RED. I would require your assistance in solving this issue. I attached some pictures below for your reference. I am running on Windows.

**Steps to replicate the issue:**

![image](https://user-images.githubusercontent.com/72122635/102007647-72ab1680-3d5d-11eb-950e-8c74bebc2218.png)

1. I navigated to the .node-red directory
_cd C:\Users\devit\node-red_
2. Ran npm install @tensorflow/tfjs-node
_C:\Users\devit\.node-red>npm install @tensorflow/tfjs-node_

![image](https://user-images.githubusercontent.com/72122635/102007878-2d87e400-3d5f-11eb-92e2-426b2534add4.png)

3. Navigated to node_module/@tensorflow/tfjs-node directory
_C:\Users\devit\.node-red>cd C:\Users\devit\.node-red\node_modules\@tensorflow\tfjs-node_
4. Ran npm install
_C:\Users\devit\.node-red\node_modules\@tensorflow\tfjs-node>npm install_

![image](https://user-images.githubusercontent.com/72122635/102007906-6758ea80-3d5f-11eb-8060-f50bf371c392.png)

5. Ran npm install node-red-contrib-tf-model
_C:\Users\devit\.node-red\node_modules\@tensorflow\tfjs-node>npm install node-red-contrib-tf-model_

However, the return message prompted me to install version 1.4.0 for @tensorflow/tfjs-node
I uninstalled the current @tensorflow/tfjs-node and installed version 1.4.0 instead 
I repeated the above steps and ran _npm install node-red-contrib-tf-model_ and still got the same error. (Picture below)

![image](https://user-images.githubusercontent.com/72122635/102008078-7a1fef00-3d60-11eb-8bb4-bd56fcc6b8c8.png)

I would be very happy if you could tell me what am I doing wrong, apologies for the inconvenience.

Thank you very much for your time!

**Comment by yhwang** [comment]
Hi @devittok , can you try my instructions here: https://github.com/yhwang/node-red-contrib-tf-model/issues/16#issuecomment-742691599

Then we can continue if you still have any issue from there.

**Comment by devittok** [comment]
> Hi @devittok , can you try my instructions here: [#16 (comment)](https://github.com/yhwang/node-red-contrib-tf-model/issues/16#issuecomment-742691599)
> 
> Then we can continue if you still have any issue from there.

Hi @yhwang it is working now. Thanks a lot!
