### ISSUE TITLE
Tensor Input Error (Need Help)

### ISSUE THREAD

**Issue by keekeen** [yhwang/node-red-contrib-tf-model#19]
Hi @yhwang,

First of all, thank you very much for taking your time reviewing my issue.

I have managed to upload my JSON model to your node. However, I am getting the following error when trying to inject input to my model:
![image](https://user-images.githubusercontent.com/24519970/102600379-b0db7800-4159-11eb-8baa-e10314db40c3.png)

The following is my node-red flow for your reference:
![image](https://user-images.githubusercontent.com/24519970/102600507-e1231680-4159-11eb-968a-f62534b0e9cc.png)

The following is my code in the pre-processing node and output from this node, I have hard code to a tensor shape of [1, 15] to test on node-red and because that is what my model accept in my python code.
![image](https://user-images.githubusercontent.com/24519970/102600744-32cba100-415a-11eb-9f2f-102a1bfd9a0d.png)
![image](https://user-images.githubusercontent.com/24519970/102602084-fdc04e00-415b-11eb-9dfc-520252b224b7.png)

The following notebook shows that the same model accept size of 15 input.
![image](https://user-images.githubusercontent.com/24519970/102601889-b76aef00-415b-11eb-97d8-1e2a7e93f768.png)

Any advice on how to go about this error?

Thank you and regards

**Comment by keekeen** [comment]
Hello @yhwang,

Error resolved after I convert my Keras HDF5 to GraphModel format! 👍

**Comment by yhwang** [comment]
@keekeen sorry for the late response because of the holiday season. great to hear that you solve the issue. Also thanks for reading that article. FYI, we published another article related to TF.js and Node-RED here: https://developer.ibm.com/tutorials/building-a-machine-learning-node-for-node-red-using-tensorflowjs/
