### ISSUE TITLE
model.json file not accessible from BERT analysis example

### ISSUE THREAD

**Issue by sannas81** [yhwang/node-red-contrib-tf-model#27]
Hi @yhwang ,

Thanks for your work to explain how the tensorflow works with node-red. While, trying the example, I found the model.json file (https://max-cdn.cdn.appdomain.cloud/max-text-sentiment-classifier/tfjs/0.1.0/model.json) in BERT analysis is not accessible anymore. Is there any possibility to get that fixed?

Thanks

**Comment by sannas81** [comment]
Looks like this URL works fine: https://bert-sentiment.s3.us.cloud-object-storage.appdomain.cloud/model/model.json. I'll have tried to raise a PR (#28) to update the URL. Please be kind if I have made any mistake. This is first PR ever for me in github world.

**Comment by yhwang** [comment]
good that you figure it out and thanks for the PR!
let me close the issue for now.
